steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - services/replenishment_api/Dockerfile
      - -t
      - asia-south1-docker.pkg.dev/model-journal-431911-h3/warehouse-drone-ai/replenishment-api:latest
      - .
images:
  - asia-south1-docker.pkg.dev/model-journal-431911-h3/warehouse-drone-ai/replenishment-api:latest

